-- V8__rbac_seed_test_current_user.sql
-- This migration previously seeded test data (creator@example.com).
-- It has been intentionally converted to a no-op to keep production schemas free of test-only data.
-- Test environments now seed data via src/test/resources/db/migration/V900__test_seed_current_user.sql
